title: Skill-IT: Getting Started with AI
description: A brief how-to in order to get started with AI
remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown
domain: cmanderskronquist.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cmanderskronquist.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /getting_started_with_ai/docs/      # place folder name if the site is served in a subfolder
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
